#默认连接名称
default: mysql

#连接对象
connections:
  mysql:
    name: test
    driver: mysql
    host: 127.0.0.1
    port: 3308
    userName: root
    password: root
    charset: utf8mb4
    database: test
    maxIdleConns: 100
    maxOpenConns: 300
    connMaxLifetime: 30
    read:
      - name: test2
        host: 192.168.0.134
        port: 33099
        database: test2
      - name: test3
        host: 192.168.0.134
        port: 33099
        database: test3
  mysql2:
    host: 127.0.0.1
    name: testb
    driver: mysql
    port: 3308
    userName: root
    password: root
    charset: utf8mb4
    database: testb
    maxIdleConns: 100
    maxOpenConns: 300
    connMaxLifetime: 30
    read:
      - name: readConnection
        port: 33099
        host: 192.168.0.134
        database: test4
    write:
      - name: writeConnection
        port: 33099
        host: 192.168.0.134
        database: test5